### ISSUE TITLE
Able to set ringtone for individual contacts

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [you-apps/ConnectYou#305]
### Describe your suggested feature

As the title said. This will be a very useful feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
ConnectYou doesn't have a call feature. How does setting individual ringtones make sense to you?

**Comment by M00NJ** [comment]
> BTW, add the festure of to be able editing "custom" to any text you want on the phone field would be useful, too.

See: #203

**Comment by JaneValleyhasBtaken** [comment]
Hi
The Simple Contact Pro doesn't have the call feature neither, but it is able to set ringtone

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by M00NJ** [comment]
Today is your lucky day it seems. It looks like ConnectYou will get a dialing feature, so I'll leave this open. Otherwise it wouldn't have made much sense to me.

**Comment by JaneValleyhasBtaken** [comment]
😘

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Bnyro** [comment]
Even if we have dialing support, I still think that this feature is useless ...

**Comment by JaneValleyhasBtaken** [comment]
It is like, there is someone very special to you and you want every notification from them catch your attention. So this is why I request this feature.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Bnyro** [comment]
Not planned because literally nobody uses different ringtones per contact. If you want to, use an other app please.

**Comment by alcoolfire** [comment]
@Bnyro: "Literally nobody"? @JaneValleyhasBtaken does. I do. All the people who pressed the developer of Simple Contacts to add the individual ringtones feature do. Google is well known for killing features that many people still use, yet even they haven't gotten rid of individualized ringtones. Some of us need to audibly triage incoming calls in the workplace. Some of us can't see very well. Other reasons abound.

@M00NJ: The reason it makes sense to include this feature in a contacts app is because individualized ringtones are stored in the contacts database. Whether the app has a calling feature is not relevant. We want our contacts app to fully manage our contacts database.

Please reconsider adding this feature. There are a lot of disaffected Simple Contacts users hunting for a replacement and ConnectYou might be a good candidate, if it had feature parity.

**Comment by JaneValleyhasBtaken** [comment]
Thanks, you just speak out exactly what am I thinking about

**Comment by JaneValleyhasBtaken** [comment]
I would said it might be also an accessibility feature for blind people

**Comment by Bnyro** [comment]
Feel free to open a pull request if you deserve to.
